"""Shared visual metrics for policy catalog views."""

from PySide6.QtCore import QSize

POLICY_ICON_SIZE = QSize(40, 40)
POLICY_COMPACT_ROW_HEIGHT = 52
POLICY_MEDIA_ROW_HEIGHT = 64
POLICY_TREE_INDENTATION = 22
POLICY_COMPACT_BADGE_COLUMN_WIDTH = 116
POLICY_MEDIA_BADGE_COLUMN_WIDTH = 124
