"""Restricted structural interface supplied to stateful workflows."""

from __future__ import annotations

from typing import Any, Protocol

from farm_merge_valet.automation.action_control import ActionCoordinator
from farm_merge_valet.automation.board_space import BoardSpaceAssessment
from farm_merge_valet.automation.phases import Phase
from farm_merge_valet.automation.runtime import GameRuntime, RuntimeCapability, RuntimeHealth
from farm_merge_valet.config import AppConfig
from farm_merge_valet.core.board import BoardGrid


class WorkflowContext(Protocol):
    """Capabilities workflows need without depending on the orchestration implementation."""

    config: AppConfig
    runtime: GameRuntime
    board: BoardGrid
    phase: Phase
    _live_cells: dict[Any, Any]
    _storage_bubbles: tuple[Any, ...] | None
    _marketplace_catalog: tuple[Any, ...]

    @property
    def _action_event_context(self) -> Any: ...
    @property
    def _action_key(self) -> Any: ...
    @property
    def _action_signature(self) -> Any: ...
    @property
    def _describe_cell(self) -> Any: ...
    @property
    def _interaction_event_context(self) -> Any: ...
    @property
    def _interaction_succeeded(self) -> Any: ...
    @property
    def _merge_action_succeeded(self) -> Any: ...
    @property
    def _shop_order_for_action(self) -> Any: ...
    @property
    def _shop_policy(self) -> Any: ...
    @property
    def _submit_interaction(self) -> Any: ...
    @property
    def _submit_merge(self) -> Any: ...
    @property
    def _submit_shop_action(self) -> Any: ...

    def _now(self) -> float: ...
    def _actions(self) -> ActionCoordinator: ...
    def _set_phase(self, phase: Phase) -> None: ...
    def _defer_idle(self) -> None: ...
    def _report_wait(self, reason: str, **context: object) -> None: ...
    def clear_wait_state(self) -> None: ...
    def _ensure_capability(
        self, health: RuntimeHealth, capability: RuntimeCapability, *, label: str | None = None
    ) -> bool: ...
    def _request_board_space(
        self,
        health: RuntimeHealth,
        board_space: BoardSpaceAssessment,
        *,
        requester: str,
        required_empty_cells: int,
        resume_phase: Phase,
        action_key: tuple[object, ...] = (),
    ) -> bool: ...
    def _schedule_next_item_action(self, now: float) -> None: ...
    def _record_action_no_progress(self, action: str, **context: object) -> None: ...
